# Generated by Django 4.2.16 on 2024-09-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
